### PR TITLE
Configure face colors

### PR DESCRIPTION
**Pull request by AdeilsonESilva**
Hi, @merpig 

Changes:
- Updated the dependencies
- Installed the styled-components lib
- Created a new modal for face color settings

I am open for comments on these adjustments.

### CODE REVIEW

**Comment by merpig** [comment]
I'm excited to check out your changes, I'll take a look at them this weekend and get back to you with my thoughts!

**Comment by luckyluke80** [comment]
I checked out the PR and tried to run it, but I get an error:

```
TypeError: Cannot read properties of undefined (reading '0')
    at pieces (http://localhost:3000/MegaMinx/static/js/bundle.js:8131:12)
    at revisedSolver (http://localhost:3000/MegaMinx/static/js/bundle.js:8541:72)
    at http://localhost:3000/MegaMinx/static/js/bundle.js:162:84
  ```

I think there are still some calls without handing over the color array. (e.g. `let allPieces = pieces(deca);` 

Would it be possible to have the colors as global array, so it does not need to be handed over?

**Comment by merpig** [comment]
> Hi, @merpig
> 
> Changes:
> 
> * Updated the dependencies
> * Installed the styled-components lib
> * Created a new modal for face color settings
> 
> I am open for comments on these adjustments.

I like the suggestion and how the color settings interface is formatted! I tested out the implementation and the solver doesn't behave as intended. Some how the moves are getting popped out of the solve list after each move.

So after some more digging, the Solver component is spam reloading which is rerunning the solver each time. I'm not sure if the issue is tied directly with context, but I implemented my own fix for simplifying the color arrays and allowing for changing default colors without using context for now.

**Comment by merpig** [comment]
I've implemented some of your changes @AdeilsonSilvaBW by copying what I can that works with the changes I made to get around some underlying issues and credited code in files and contribution in the README. Thank you for your suggestions!

**Pull request closed without merging**
